### ISSUE TITLE
Disable custom order on specific places

### ISSUE THREAD

**Issue by uiliw** [yikesinc/yikes-simple-taxonomy-ordering#6]
How can i use my custom order instead of dragndrop order on some places?

```
$args2 = array(
'orderby' => 'name',
'order' => 'ASC',
'show_count' => 1,
'title_li' => '',
'taxonomy' => 'categoria'
);
wp_list_categories($args2);
```

**Comment by kpu23** [comment]
Hi @uiliw,

You can order by name in the way your code shows (e.g. `'orderby' => 'name'`).

Is it not working? What's returned? I just tested a few different orderby's and they're all working on my side.

Let me know,
Kevin.

**Comment by uiliw** [comment]
hey @kpu23 !

Its always returning the plugin's order, no matter what i change, if i disable the plugin, it works how i want!

1. First I enabled the two custom taxonomies i have, that is "Categoria" and "Linha",
2. On taxonomies page i ordered how i wanted because on some pages they need to show like this order, but only in one place, in taxonomy.php's sidebar i placed that code above to order by name, and not by the plugins order.

I've tested differente orderby's also an nothing happens.. :/

**Comment by EvanHerman** [comment]
Hi @uiliw I believe the terms are filtered using the drag and drop order across the entire site due to the following filter:
https://github.com/yikesinc/yikes-inc-simple-taxonomy-ordering/blob/master/yikes-custom-taxonomy-order.php#L114-L116

You should be able to remove the filter where you need.

`remove_filter( 'terms_clauses', array( $this, 'yikes_alter_tax_order' ), 10 );`

**Comment by DobleD** [comment]
Old post but same problem here. 

I need to call wp_dropdown_categories ordering by name but always returns the drag'n drop order.

I followed EvanHerman idea to disable the filter before calling wp_dropdown_categories but can access the yikes_alter_tax_order filter with _$this_.

The only solution i found is modifyng line 260 in yikes-custom-taxonomy-order.php to 
`$yikes_tax_order = new Yikes_Custom_Taxonomy_Order();`
Now i can access the filter with `global $yikes_tax_order;`

Is it correct? There is another solution? otherwise, can you please modify your plugin for future versions?

Thanks in advance.

**Comment by EvanHerman** [comment]
@DobleD I've issued a PR against the plugin to update the main plugin file, which would allow removing the filter easier. See #20 for example code and to track progress.

**Comment by DobleD** [comment]
Thanks! :)
